---
redisCluster:
  clusterSize: 3
  image: quay.io/opstree/redis
  tag: v6.2
  imagePullPolicy: IfNotPresent
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  leaderServiceType: ClusterIP
  followerServiceType: ClusterIP
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

redisExporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  tag: "1.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

# priorityClassName: "-"

nodeSelector: {}
  # memory: medium

storageSpec:
  volumeClaimTemplate:
    spec:
      # storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  #   selector: {}

securityContext: {}
  # runAsUser: 1000

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: disktype
  #         operator: In
  #         values:
  #         - ssd
