global:
  name:
    appName: redis
    appLabel:
      app: redis
      environment: prod
  replicaCount: 1
  containers:
    - name: redis
      image: redis
      tag: "6.2.2"
      pullPolicy: Always
      # command:
      #   - "--default-authentication-plugin=mysql_native_password"
      ports:
       - name: client
         port: 6379
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     value: "test"
      #   - name: MYSQL_DATABASE
      #     value: admin
      #   - name: MYSQL_USER
      #     value: admin
      #   - name: MYSQL_PASSWORD
      #     value: admin
      #   - name: MYSQL_ALLOW_EMPTY_PASSWORD
      #     value: "no"

      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "0.5"
      livenessProbe:
        tcpSocket:
           port: 6379
      readinessProbe:
        tcpSocket:
          port: 6379

      volumeMounts:
      - name: tz-config
        mountPath: /etc/localtime
      

  affinity:
    podAntiAffinity:
      weight: 100
      key: app
      values:
      - redis
      topologyKey: kubernetes.io/hostname
  service:
    type: ClusterIP
    headless: true
    ports:
      - port: 6379
        targetPort: 6379
  volumes:
    - name: tz-config
      hostPath:
         path: /usr/share/zoneinfo/Asia/Kolkata
